name: Checks

on:
  pull_request:

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # required to get all history, not just commit that triggers current run
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v2
        with:
          configFile: .commitlintrc.js
